"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.lazyLoadMilitaryMedicine = exports.lazyLoadMedicalAdministration = exports.lazyLoadDivingMedicine = exports.lazyLoadAviationMedicine = exports.lazyLoadWorkAbility = exports.lazyLoadMedicalRights = exports.lazyLoadIndustryConsulting = exports.lazyLoadCausalLinkAssessment = exports.lazyLoadAccessibility = exports.lazyLoadLocation = exports.lazyLoadAbout = void 0;
var lazyLoadAbout = function () { return Promise.resolve().then(function () { return require('./pages/about/about.component'); }); };
exports.lazyLoadAbout = lazyLoadAbout;
var lazyLoadLocation = function () { return Promise.resolve().then(function () { return require('./pages/location/location.component'); }); };
exports.lazyLoadLocation = lazyLoadLocation;
var lazyLoadAccessibility = function () { return Promise.resolve().then(function () { return require('./pages/accessibility/accessibility.component'); }); };
exports.lazyLoadAccessibility = lazyLoadAccessibility;
var lazyLoadCausalLinkAssessment = function () { return Promise.resolve().then(function () { return require("./pages/services/occupational-medicine/causal-link-assessment/causal-link-assessment.component"); }); };
exports.lazyLoadCausalLinkAssessment = lazyLoadCausalLinkAssessment;
var lazyLoadIndustryConsulting = function () { return Promise.resolve().then(function () { return require("./pages/services/occupational-medicine/industry-consulting/industry-consulting.component"); }); };
exports.lazyLoadIndustryConsulting = lazyLoadIndustryConsulting;
var lazyLoadMedicalRights = function () { return Promise.resolve().then(function () { return require("./pages/services/occupational-medicine/medical-rights/medical-rights.component"); }); };
exports.lazyLoadMedicalRights = lazyLoadMedicalRights;
var lazyLoadWorkAbility = function () { return Promise.resolve().then(function () { return require("./pages/services/occupational-medicine/work-ability/work-ability.component"); }); };
exports.lazyLoadWorkAbility = lazyLoadWorkAbility;
var lazyLoadAviationMedicine = function () { return Promise.resolve().then(function () { return require("./pages/services/additional-services/aviation-medicine/aviation-medicine.component"); }); };
exports.lazyLoadAviationMedicine = lazyLoadAviationMedicine;
var lazyLoadDivingMedicine = function () { return Promise.resolve().then(function () { return require("./pages/services/additional-services/diving-medicine/diving-medicine.component"); }); };
exports.lazyLoadDivingMedicine = lazyLoadDivingMedicine;
var lazyLoadMedicalAdministration = function () { return Promise.resolve().then(function () { return require("./pages/services/additional-services/medical-administration/medical-administration.component"); }); };
exports.lazyLoadMedicalAdministration = lazyLoadMedicalAdministration;
var lazyLoadMilitaryMedicine = function () { return Promise.resolve().then(function () { return require("./pages/services/additional-services/military-medicine/military-medicine.component"); }); };
exports.lazyLoadMilitaryMedicine = lazyLoadMilitaryMedicine;
